# Generated by Django 5.2.1 on 2025-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customerName", models.CharField(max_length=100)),
                ("customerPhone", models.CharField(max_length=15)),
                ("customerEmail", models.EmailField(max_length=254)),
                (
                    "customerAddress",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "vehicleMake",
                    models.CharField(
                        choices=[
                            ("honda", "Honda"),
                            ("royalEnfield", "Royal Enfield"),
                            ("tvs", "TVS"),
                            ("marutiSuzuki", "Maruti Suzuki"),
                            ("hyundai", "Hyundai"),
                            ("mahindra", "Mahindra"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vehicleModel", models.CharField(max_length=255)),
                ("vehicleYear", models.PositiveIntegerField()),
                ("registrationNumber", models.CharField(max_length=20)),
                (
                    "serviceType",
                    models.CharField(
                        choices=[
                            ("generalService", "General Service"),
                            ("majorRepair", "Major Repair"),
                            ("accidentalRepair", "Accidental Repair"),
                            ("breakService", "Break Service"),
                            ("engineCheckup", "Engine Check-Up"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("preferredDate", models.DateField()),
                ("preferredTime", models.CharField(max_length=20)),
                (
                    "issueDescription",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of selected issues"
                    ),
                ),
                ("bookingDate", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending")),
            ],
            options={
                "ordering": ["bookingDate"],
            },
        ),
    ]
