# Generated by Django 5.2.1 on 2025-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("email_address", models.EmailField(max_length=254)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tata_model",
                    models.CharField(
                        choices=[
                            ("nexon", "Nexon"),
                            ("harrier", "Harrier"),
                            ("punch", "Punch"),
                            ("altroz", "Altroz"),
                            ("tiago", "Tiago"),
                            ("tigorev", "Tigor EV"),
                            ("safari", "Safari"),
                            ("sumo", "Sumo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reg_year", models.PositiveIntegerField()),
                ("reg_number", models.CharField(max_length=20)),
                ("odometer_reading", models.PositiveIntegerField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("regularMaintenance", "Regular Maintenance"),
                            ("repairService", "Repair Service"),
                            ("warrantyService", "Warranty Service"),
                            ("amcService", "AMC Service"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "common_issues",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of selected issues"
                    ),
                ),
                ("additional_details", models.TextField(blank=True, null=True)),
                ("preferred_date", models.DateField()),
                ("preferred_time_slot", models.CharField(max_length=20)),
                (
                    "service_pref",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of preferences"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
