# Generated by Django 5.2.1 on 2025-05-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(default="Pending", max_length=30),
        ),
    ]
