# Generated by Django 5.2.1 on 2025-05-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_servicerequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="bookingId",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
