# Generated by Django 5.2.1 on 2025-05-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_servicerequest_bookingid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
